server:
  port: 8089
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: car-client
kafka:
  topic:
    car:
      request: car.request
      reply: car.reply
  request-reply:
    timeout-ms: 1000
